app: 
  name: IntraleFunction
  microservices: false
  instantiate:
    factory: true
    provider: true
    read: true
    signin: true
    signup: true
    delete: true
    deletelink: true
    passwordRecovery: true
    confirmPasswordRecovery: true
    link: true
    getlink: true
    validatelink: true
    validateToken: true
  security:
    read: readUser
    getlink: readUser
    delete: deleteUser
    deletelink: deleteUser
  activity:
    enabled: ${validate.enabled:false}
    maxInactivity: 60000
    fixedDelay: 30s
    initialDelay: 15s
  aws:
    region: us-east-2
  cognito:
    clientId: 1ve1nokbjnmhk1adiben0a9iao
    userPoolId: us-east-2_rLbLF8HCb
    access: ${cognito.access}
    secret: ${cognito.secret}
    connectionTimeout: 2000
    readTimeout: 2000
    urlPrefix: https://cognito-idp.
    urlMid: .amazonaws.com/
    urlSufix: /.well-known/jwks.json
  database:
    access: ${database.access}
    secret: ${database.secret}
  signup:
    temporaryPassword:
      length: 8
      returned: false
      #complex: false
  