name: CI intrale-users

on:
  push:
    branches: [ main ]

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Call intrale-test
      if: (github.event.action != 'ping_parent') && (github.event.action != 'pong_parent') 
      run: |
         curl -X POST https://api.github.com/repos/intrale/intrale-test/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.MAVEN_SERVER_PASSWORD }} \
          --data '{"event_type": "ping_child", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'     
      - uses: actions/checkout@master
        if: (github.event.action == 'ping_parent') || (github.event.action == 'pong_parent') 
      - uses: actions/setup-java@v1
        if: (github.event.action == 'ping_parent') || (github.event.action == 'pong_parent')
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: generate package
        if: (github.event.action == 'ping_parent') || (github.event.action == 'pong_parent')
        env:
            VERSION: ${{ secrets.VERSION }}  
            MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
            MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
            COGNITO_ACCESS: ${{ secrets.COGNITO_ACCESS }} 
            COGNITO_SECRET: ${{ secrets.COGNITO_SECRET }} 
            DATABASE_ACCESS: ${{ secrets.DATABASE_ACCESS }} 
            DATABASE_SECRET: ${{ secrets.DATABASE_SECRET }} 
        run: | 
             sed -i "s/DEV/$VERSION/gi" pom.xml
             cat pom.xml
             mkdir -p ~/.m2
             echo "<settings><servers><server><id>github</id><username>${MAVEN_SERVER_USERNAME}</username><password>${MAVEN_SERVER_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
             mvn clean compile package
      - name: deploy lambda
        if: (github.event.action == 'ping_parent') || (github.event.action == 'pong_parent')
        uses: yvesgurcan/deploy-lambda-function@master
        with:
          package: ./target/users.jar
          function-name: users
          AWS_REGION: ${{ secrets.AWS_DEPLOY_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_DEPLOYER_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_DEPLOYER_SECRET_KEY }} 
 
