name: CI intrale-users

on:
  push:
    branches: [ main ]
  repository_dispatch:       
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@master
      - name: JDK Setup
        uses: actions/setup-java@v2
        with:
            java-version: '11' # The JDK version to make available on the path.
            distribution: 'temurin'
            java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
            architecture: x64 # (x64 or x86) - defaults to x64
      - name: Version definition
        env:
          REL_USERS: ${{ secrets.REL_USERS }}
          EVO_USERS: ${{ secrets.EVO_USERS }}
          REV_USERS: ${{ secrets.REV_USERS }}
        run: |
          echo "REV_USERS=$(($REV_USERS+1))" >> $GITHUB_ENV
          if [[ $REV_USERS > 21 ]]; then
            echo "REV_USERS=0" >> $GITHUB_ENV 
            echo "EVO_USERS=$(($EVO_USERS+1))" >> $GITHUB_ENV
          fi
          if [[ $EVO_USERS > 11 ]]; then
            echo "EVO_USERS=0" >> $GITHUB_ENV 
            echo "REL_USERS=$(($REL_USERS+1))" >> $GITHUB_ENV
          fi
          echo "REL_USERS=$(($REL_USERS))" >> $GITHUB_ENV
          echo "EVO_USERS=$(($EVO_USERS))" >> $GITHUB_ENV
          echo "VER_USERS=${REL_USERS}.${EVO_USERS}.${REV_USERS}" >> $GITHUB_ENV
          echo "VER_USERS_TEXT=${REL_USERS}_${EVO_USERS}_${REV_USERS}" >> $GITHUB_ENV       
      - name: Save REL_USERS
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'REL_USERS'
          value: ${{ env.REL_USERS }}
          repository: 'intrale'
          token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
          org: true
          visibility: 'all'
      - name: Save EVO_USERS
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'EVO_USERS'
          value: ${{ env.EVO_USERS }}
          repository: 'intrale'
          token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
          org: true
          visibility: 'all'
      - name: Save REV_USERS
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'REV_USERS'
          value: ${{ env.REV_USERS }}
          repository: 'intrale'
          token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
          org: true
          visibility: 'all'
      - name: Save VER_USERS
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'VER_USERS'
          value: ${{ env.VER_USERS }}
          repository: 'intrale'
          token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
          org: true   
          visibility: 'all'              
      - name: Deploy to Github Package Registry
        env:
          VER_PARENT: ${{ secrets.VER_PARENT }}
          VER_COMMONS: ${{ secrets.VER_COMMONS }}
          VER_TEST: ${{ secrets.VER_TEST }}
          MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
          MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
          COGNITO_ACCESS: ${{ secrets.COGNITO_ACCESS }} 
          COGNITO_SECRET: ${{ secrets.COGNITO_SECRET }} 
          DATABASE_ACCESS: ${{ secrets.DATABASE_ACCESS }} 
          DATABASE_SECRET: ${{ secrets.DATABASE_SECRET }} 
        run: |
          sed -i "s/DEV_PARENT/${VER_PARENT}/gi" pom.xml
          sed -i "s/DEV_COMMONS/${VER_COMMONS}/gi" pom.xml
          sed -i "s/DEV_TEST/${VER_TEST}/gi" pom.xml
          sed -i "s/DEV_USERS/${VER_USERS}/gi" pom.xml
          sed -i "s/DEV_USERS/${VER_USERS}/gi" ./core/pom.xml
          sed -i "s/DEV_USERS/${VER_USERS}/gi" ./services/pom.xml
          sed -i "s/DEV_USERS/${VER_USERS}/gi" ./client/pom.xml
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${MAVEN_SERVER_USERNAME}</username><password>${MAVEN_SERVER_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn clean compile package install
          mvn -e -X deploy
      - name: deploy lambda
        uses: yvesgurcan/deploy-lambda-function@master
        with:
          package: ./services/target/users-services.jar
          function-name: users
          AWS_REGION: ${{ secrets.AWS_DEPLOY_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_DEPLOYER_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_DEPLOYER_SECRET_KEY }} 
      - name: Tag Branch  
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "VER_${{ env.VER_USERS_TEXT }}"
          message: "VER_${{ env.VER_USERS_TEXT }}"
      - name: Delete old packages
        uses: actions/delete-package-versions@v3
        with:
          owner: 'llarreta'
          repo: 'intrale'
          package-name: 'ar.com.intrale.users'
          min-versions-to-keep: 3
          token: ${{ secrets.MAVEN_SERVER_PASSWORD }}             