name: Deploy Lambda

on:
  push:
    branches: [ master ]

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: generate package
        env:
            MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
            MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
            COGNITO_ACCESS: ${{ secrets.COGNITO_ACCESS }} 
            COGNITO_SECRET: ${{ secrets.COGNITO_SECRET }} 
        run: | 
             mkdir -p ~/.m2
             echo "<settings><servers><server><id>github</id><username>${MAVEN_SERVER_USERNAME}</username><password>${MAVEN_SERVER_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
             mvn clean compile package
      - name: deploy lambda
        uses: yvesgurcan/deploy-lambda-function@master
        with:
          package: ./target/users.jar
          function-name: users
          AWS_REGION: ${{ secrets.AWS_DEPLOY_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_DEPLOYER_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_DEPLOYER_SECRET_KEY }} 
 
